bug fix
running another addon from text editor in 3DView with F3 was making errors in console for each operator because of the poll:
Python: Traceback (most recent call last):
  File "C:\Users\dd200\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Trim-Whitespace-Change-Case-and-Split-Join-Lines.py", line 173, in poll
    return (context.space_data.text and context.area.type == 'TEXT_EDITOR')
AttributeError: 'SpaceView3D' object has no attribute 'text'
so I just inverted to check 3Dview at first